### ISSUE TITLE
[Feature]: Oidc integration

### ISSUE THREAD

**Issue by JensAc** [glasskube/operator#252]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching

### Is this feature request related to a problem?

No

### Problem Description

We want to configure an oidc provider for all applications spawned by the glasskube-operator. 

### Solution Description

A very simple solution would be to extend the app `CRD`s by e.g.

```yaml
oidc:
  properties:
    name:
      type: string
    clientId:
      type: string
    clientSecret:
      type: string
    discoveryEndpoint:
      type: string
  type: object
``` 
and simply pass these additional bits of configuration to the apps.

### Benefits

One could configure oidc without any manual interaction.

### Potential Drawbacks

The resources would contain secret data, if the problem is approached as proposed. This might be acceptable for the sake of describing the app to be installed in a single resource. Of course, we could also think about specifying a `secretRef` and fetch the secret data from there. However, this would require the secret to exists, when an app should be installed. 
What do you think?
