### ISSUE TITLE
Odoo Reconciler constantly reconciles

### ISSUE THREAD

**Issue by pmig** [glasskube/operator#468]
With debug logs activated, you could see the OdooReconciler constantly being executed.

**Steps to reproduce:**

Deploy an odoo:

```yaml
apiVersion: "glasskube.eu/v1alpha1"
kind: Odoo
metadata:
  name: odoo
  namespace: odoo
spec:
  version: "16.0.20230901"
  host: odoo.mycompany.eu
  demoEnabled: false
  database:
    storage:
      size: "12Gi"
```
